name: Gem

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
    - name: Build
      run: |
        gem build *.gemspec
    - name: Publish to RubyGems
      run: |
        gem push --verbose *.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_TOKEN}}
